version: "2.0"

services:
  web:
    image: capinix/cerberusd:lastest
    env:
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvUFlqYapuKjCFpaOFzmiSMBf6a2neFc5g5K+At7EpQlX5Po97FA6WOMhpwE/fu18qMVivZ9cx0yyY2hmrN8GzJ/yreqXjfxQzf7hG2ztyqXM32kdCSHc1bdl7t03RPdVJOMAFJkPLqXz/B39KPXgidswMGyyhZdCSy2Fug1H3x8IiBOW23FoUxbB6tk6/AJQaYEccd8Ohnf9gk0fdzSlCqnh5206WmDpanXQy7gGwXkyPs3AAE7mKYEvoIJSys7c0WmrwbfNJcj21E9HSgm48EgsAb0C6+fVE3E8s6JV33dehQ/DBnus/A8XQ8NHXz6PvJCPC9QuPY7ooNirUhwxBw==
	  - USER_NAME=node
    expose:
      - port: 22
        as: 22000
        to:
          - global: true
      - port: 1317
        as: 1317
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 160Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 30

deployment:
  web:
    dcloud:
      profile: web
      count: 1
